name: GitHub Actions Pull Request

on:
  push:
    paths:
      - "resolve-java-sources-and-javadocs/**"
      - ".github/**"

env:
  LEIN_ROOT: true

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-18.04", "macOS-latest"]
        java-version: ["8", "11"]
        integration-test-parallelism: ["1", "4"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - run: java -version
      - uses: DeLaGuardo/setup-clojure@91054c3
        with:
          cli: '1.10.1.469'
          lein: 2.9.4
      # should match with `#'integration-test/lein`:
      - run: which lein
      - name: run tests
        working-directory: ./resolve-java-sources-and-javadocs
        run: lein test
        env:
          no_eval_in_leiningen: true
      - name: exercise the plugin over a variety of real-world projects
        working-directory: ./resolve-java-sources-and-javadocs
        run: lein integration-test
        env:
          no_eval_in_leiningen: true
          integration_test_parallelism: ${{ matrix.integration-test-parallelism }}
