name: GitHub Actions Pull Request

on:
  push:
    paths:
      - "resolve-java-sources-and-javadocs/**"
      - ".github/**"

env:
  LEIN_ROOT: true
  JAVA_VERSION: 8

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java-version: ["8"]
        integration-test-parallelism: ["1"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - run: java -version
      - uses: DeLaGuardo/setup-clojure@91054c3
        with:
          cli: '1.10.1.469'
          lein: 2.9.4
      - name: run tests
        working-directory: ./resolve-java-sources-and-javadocs
        run: lein test
        env:
          no_eval_in_leiningen: true
      - name: exercise the plugin over a variety of real-world projects
        working-directory: ./resolve-java-sources-and-javadocs
        run: lein integration-test
        env:
          no_eval_in_leiningen: true
          integration_test_parallelism: ${{ matrix.integration-test-parallelism }}
